USE [testdb]
GO
-- 菜单表 --
CREATE TABLE MenuData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
PID CHAR(32) NULL,
ParentPath VARCHAR(2000) NULL,
Name NVARCHAR(50) NOT NULL,
Url NVARCHAR(1000) NULL,
[Level] INT DEFAULT(1) NOT NULL,
Sort INT DEFAULT(1) NOT NULL
)
GO
-- 文件表 --
CREATE TABLE FileData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
Name NVARCHAR(500) NOT NULL,
Url NVARCHAR(1000) NULL,
Sort INT DEFAULT(1) NOT NULL
)
GO
-- 页面元素表 --
CREATE TABLE PageData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
Name NVARCHAR(500) NOT NULL,
Code NVARCHAR(50) NOT NULL
)
GO
-- 模块操作表 --
CREATE TABLE ModelData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
Name NVARCHAR(500) NOT NULL,
Md_NameSpace NVARCHAR(500) NULL,
Method NVARCHAR(500) NULL,
Code NVARCHAR(50) NULL
)
GO
-- 权限表 --
CREATE TABLE PermData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
Name NVARCHAR(500) NOT NULL,
[Description] NVARCHAR(500) NOT NULL
)
GO
-- 角色表 --
CREATE TABLE RoleData
(
ID CHAR(32) PRIMARY KEY NOT NULL,
Name NVARCHAR(500) NOT NULL,
[Description] NVARCHAR(500) NULL,
Sort INT DEFAULT(1) NOT NULL
)
GO
-- 权限与功能关系表 --
CREATE TABLE PermToFunc
(
DataType INT NOT NULL,
Perm_ID CHAR(32) NOT NULL,
Func_ID CHAR(32) PRIMARY KEY(Perm_ID,Func_ID) NOT NULL
)
GO
-- 角色与权限关系表 --
CREATE TABLE RoleToPerm
(
Role_ID CHAR(32) NOT NULL,
Perm_ID CHAR(32) PRIMARY KEY(Role_ID,Perm_ID) NOT NULL
)
GO